import SlotLockController from "../controllers/implementation/SlotLockController";
import { UserController } from "../controllers/implementation/UserController";
import { AppointmentRepository } from "../repositories/implementation/AppointmentRepository";
import { DoctorRepository } from "../repositories/implementation/DoctorRepository";
import { UserRepository } from "../repositories/implementation/UserRepository";
import { WalletRepository } from "../repositories/implementation/WalletRepository";
import { PaymentService } from "../services/implementation/PaymentService";
import { SlotLockService } from "../services/implementation/SlotLockService";
import { UserService } from "../services/implementation/UserService";
import { WalletPaymentService } from "../services/implementation/WalletPaymentService";
import { WalletService } from "../services/implementation/WalletService";
import { RevenueDistributionService } from "../services/implementation/RevenueDistributionService";

const userRepository = new UserRepository();
const walletRepository = new WalletRepository();
const paymentService = new PaymentService();
const appointmentRepo = new AppointmentRepository();
const doctorRepo = new DoctorRepository();
const slotLockService = new SlotLockService(appointmentRepo, userRepository, doctorRepo);
const walletService = new WalletService(walletRepository);
const revenueDistributionService = new RevenueDistributionService(walletService);
const walletPaymentService = new WalletPaymentService(walletService, appointmentRepo, revenueDistributionService);
const userService = new UserService(walletPaymentService,userRepository, paymentService, slotLockService, walletService);
export const userController = new UserController(userService, paymentService);
export const slotLockController = new SlotLockController(slotLockService);